name: Coding Standards

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pint:
    name: Pint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install
      - name: Setup env file
        run: cp .env.example .env
      - name: Configure application encryption key
        run: php artisan key:generate
      - name: Pint check
        run: ./vendor/bin/pint --test

  larastan:
    name: Larastan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install
      - name: Setup env file
        run: cp .env.example .env
      - name: Configure application encryption key
        run: php artisan key:generate
      - name: Larastan check
        run: ./vendor/bin/phpstan analyse
